title = "metadata for oscar CI run"

# keep it small to prevent job-explosion
[env]
os = [ "ubuntu-latest" ]
julia-version = [ "~1.6.0-0" ]

# packages not listed here will use the latest release
[pkgs]
Oscar = [ "master", "release" ]
Hecke = [ "master", "release" ]

[include]
  [include.macos]
  Oscar = "master"
  os = "macos-latest"
  julia-version = "~1.6.0-0"

  [include.julia]
  Oscar = "master"
  julia-version = "1.5"
  os = "ubuntu-latest"
